In [8]:
import sys
print(sys.executable)
import sklearn
print(sklearn.__version__)

/usr/bin/python3.13
1.7.2


In [1]:
import torch
print(torch.__version__)
Vector=torch.tensor([1,2,3,4,5])
print(Vector)

2.7.1a0
tensor([1, 2, 3, 4, 5])


Scalar is a single number or Zero Dimensional Tensor

In [2]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
#Scalar Dimensions
print(scalar.ndim)
#Retriving the Number from the Tensor Scalar
print(scalar.item())

tensor(7)
0
7


Vector is Single Dimensionals Array whcih has many Elements or Values

In [3]:
#Creating the Vectors
Vector=torch.tensor([1,2,3,4,5])
print("The Created Vector is ",Vector)
#Dimensions of the Vector
print(Vector.ndim)
#Shape of the Vector=> This will Return the 5 cause the Vector inside 5 Elements Are there
print(Vector.shape)

The Created Vector is  tensor([1, 2, 3, 4, 5])
1
torch.Size([5])


In [4]:
Vector=torch.tensor([1,2,3,4,5],dtype=torch.float32)
print(Vector)
print(Vector.ndim)
print(Vector.dtype)
# print(Vector.item())

tensor([1., 2., 3., 4., 5.])
1
torch.float32


Matrix:Rectangular arrangement of the Elements is Called Matrix

In [5]:
#Creating the Matrix
Matrix=torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
print(Matrix)
#Type
print(type(Matrix))
print(Matrix.ndim)
print(Matrix.shape)
# print(Matrix.flatten())
print(torch.linalg.matrix_power(Matrix,2))
print(torch.linalg.matrix_power(Matrix,2))
print(torch.linalg.matrix_power(Matrix,2))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
<class 'torch.Tensor'>
2
torch.Size([3, 3])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


Tensor:Tensor is MultiDimensional Array 

In [6]:
Tensor=torch.tensor([[[1,2,3],
                      [4,5,6]]])
print(type(Tensor))
print(Tensor.ndim)
print(Tensor.shape)

<class 'torch.Tensor'>
3
torch.Size([1, 2, 3])


Creating the Random Tensor

In [ ]:
random_tensor=torch.rand(size=(3,4),dtype=torch.float64)
print(random_tensor)
print(random_tensor.dtype)
# The flexibility of torch.rand() is that we can adjust the size to be whatever we want.
# For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).
Ranodm_image_tensor=torch.rand(size=(224,224,3))
print(Ranodm_image_tensor.shape,Ranodm_image_tensor.dtype,Ranodm_image_tensor.ndim)

Zeros And Ones

In [ ]:
#Creating the ones using torch.ones
Ones=torch.ones(size=(4,3))
print(Ones,Ones.dtype)

Creating the Range And Tensor

In [ ]:
# torch.arange(start, end, step)
# start = start of range (e.g. 0)
# end = end of range (e.g. 10)
# step = how many steps in between each value (e.g. 1)
Values=torch.arange(10,100,10)
print(Values)
print(Values.dtype)
print(Values.shape)
#Creating the Same Shape And Same Values
#NOTE:The input should be Tensors only
Same_Ones=torch.ones_like(Values)
print(Same_Ones)
Same_Zeros=torch.zeros_like(Same_Ones)
print(Same_Zeros)

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

In [14]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work
print(float_16_tensor.dtype)

torch.float16


Getting Information From Tensor

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

Arthematic Operatioons


In [ ]:
Tensor=torch.tensor([11,21,10,4])
print(Tensor+10)
print(Tensor-10)
print(Tensor*2)
print(Tensor/2)
print(Tensor%2)
#It will Give The Quotient Value or The result will round of the to down integer
print(Tensor//4)

Matrix Multiplication

In [ ]:
%%time
Matrix1=torch.tensor([[1,2,3],
                     [2,3,4],
                      [2,3,4]])
Matrix2=torch.tensor([[3,5,6],
                      [-3,5,6],
                      [5,6,7]])
#Multiplication with Element wise
print(Matrix1*Matrix2)
#Multiplication with Rows and Columns wise
print(Matrix1.matmul(Matrix2))
print(Matrix1@Matrix2)
print(torch.mm(Matrix1,Matrix2))

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(Matrix1)):
  value += Matrix1[i] * Matrix1[i]
value

In [ ]:
#Tranpose of the Matrix
Matrix=torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
#Converte the Rows to columns and Columns to Rows
print(Matrix.T)

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]],dtype=torch.float32)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

In [ ]:
Zeros=torch.zeros(size=(3,2))
print(Zeros,Zeros.dtype)

In [23]:
A=torch.arange(9).reshape(3,3)
print("The Matrix After Reshaping it",A)
#Tranpose of the Matrix..:Rows will change to columns and columns will change to Rows
print("The Tranpose of the Matrix is ",A.T)
#chek=cking the Whether the Given matrix and Trapose of the MAtrix is Same or Not
print(A==A.T)
#This is Will Truee  if the Values are same even After tranposing the Matrix
torch.arange(48).reshape(4,4,3)

The Matrix After Reshaping it tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
The Tranpose of the Matrix is  tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])


tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]])

In [26]:
import sklearn
print(sklearn.__version__)

ModuleNotFoundError: No module named 'sklearn'

In [25]:
!pip install scikit-learn


Indexing

In [8]:
A=torch.tensor([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(A)
print(A[1])
print(A[-1])
print(A[:,0:3:2])
print(A[:,-1])
print(A[:,:-1])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([5, 6, 7, 8])
tensor([ 9, 10, 11, 12])
tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])
tensor([ 4,  8, 12])
tensor([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]])


Modifing the Elements

In [9]:
A[0,0]=10
A
A[1,3]=20
A

tensor([[10,  2,  3,  4],
        [ 5,  6,  7, 20],
        [ 9, 10, 11, 12]])

In [10]:
#Exponential e power A
torch.exp(A)

tensor([[2.2026e+04, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 4.8517e+08],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

Adding Two Tensors

In [ ]:
# X=torch.arange(12,dtype=torch.float32).reshape((3,4))
# print(X)
# Y=torch.tensor([[2,3,4,5],
#                 [6,7,8,9],
#                 [1,2,3,4]],dtype=torch.float32)
# print(Y)
# print(torch.cat(X,Y),dim=0)
X=torch.randn(2,3)
print(X)
Y=torch.randn(2,3)
print(Y)
#Concadenating the two Tensors
torch.cat((X,Y),0)

In [ ]:
A=torch.randn(3,3)
print(A)
B=torch.randn(3,3)
print(torch.cat((A,B),1))

In [ ]:
import torch
print(torch.__version__)
A=torch.tensor([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]],dtype=torch.float32)
print(A)
print(A.shape)
print(A.dtype)
print(type(A))


In [ ]:
# Define tensors with requires_grad=True to track computation history
import torch
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

# Perform a computation
z = x**2 + y**3
print("Output tensor z:", z)

# Compute gradients
z.backward()
print("Gradient of x:", x.grad)
print("Gradient of y:", y.grad)

In [11]:
import sklearn
print(sklearn.__version__)

ModuleNotFoundError: No module named 'sklearn'